services:

  mysql-db:
    image: mysql:8.0

    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: notesdb

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  studyit:
    build: .
    container_name: studyit-app

    restart: on-failure

    depends_on:
      - mysql-db

    ports:
      - "8080:8080"

volumes:
  mysql-data: